### ISSUE TITLE
How to handle multiple torify|torsocket requests using multi-tor?

### ISSUE THREAD

**Issue by crymates** [jseidl/Multi-TOR#3]
E.g. we have

`torify curl ifconfig.me`

How to create torify2, torify3, torify4 and others to handle multiple requests with different connections simultanously?

So that we can start multiple scripts using different connections.

**Like:**
```
bash_1.sh
torify curl ifconfig.me
...

bash_2.sh
torify2 curl ifconfig.me
...

bash_3.sh
torify3 curl ifconfig.me
...
```

**Comment by jseidl** [comment]
Please refer to
https://www.slideshare.net/jseidl/slides-the-jerichoattackperspective

**Comment by jseidl** [comment]
Also check torify help to see if you can supply different configuration
files on the command line

**Comment by crymates** [comment]
Will do, thx.
