### ISSUE TITLE
RunAsDaemon is not compatible with relative paths

### ISSUE THREAD

**Issue by IacopoOrtis** [jseidl/Multi-TOR#4]
Starting the script on Tor 0.3.2.9 the tor comand says:

Jan 22 19:56:58.710 [notice] Tor 0.3.2.9 (git-9e8b762fcecfece6) running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2n, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jan 22 19:56:58.710 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 22 19:56:58.710 [notice] Configuration file "/usr/local/etc/tor/torrc" not present, using reasonable defaults.
Jan 22 19:56:58.712 [warn] Linelist option '__HashedControlSessionPassword' has no value. Skipping.
Jan 22 19:56:58.713 [warn] Path for DataDirectory (data/tor1) is relative and will resolve to /Users/IacopoOrtis/Dropbox/Documents/progetti/shell/Multi-TOR/data/tor1. Is this what you wanted?
Jan 22 19:56:58.713 [warn] Path for PidFile (tor1.pid) is relative and will resolve to /Users/IacopoOrtis/Dropbox/Documents/progetti/shell/Multi-TOR/tor1.pid. Is this what you wanted?
Jan 22 19:56:58.713 [warn] Failed to parse/validate config: You have specified at least one relative path (see above) with the RunAsDaemon option. RunAsDaemon is not compatible with relative paths.
Jan 22 19:56:58.713 [err] Reading config failed--see warnings above.

**Comment by IacopoOrtis** [comment]
I'll try to fix it

**Comment by IacopoOrtis** [comment]
FIXED I'll make a pull req

**Comment by theraisin** [comment]
Checkout my github sycohexor

**Comment by IacopoOrtis** [comment]
I created a pull request. Could please someone take a look at it ?

**Comment by jseidl** [comment]
Will do. Already checked through my phone and code seems all right. I'm
without internet here but will get back in a few days. Thanks for your
contribution!

**Comment by IacopoOrtis** [comment]
Thanks to you for your initial contribution and for maintaining this repository! I've also created a robust "kill.sh". Once you merge I'll make another fork and pull req.

by the way in the actual pull request there are also some mayor modifications to readme.md

**Comment by sycohexor** [comment]
yeah my script adds privoxy to it for http requests over socks :), just follow me or whatever

**Comment by jseidl** [comment]
Accepted
