### ISSUE TITLE
Not connecting - RunAsDaemon is not compatible with relative paths.

### ISSUE THREAD

**Issue by filebe777** [jseidl/Multi-TOR#6]
root@kali:~/Desktop/Multi-TOR# ./multi-tor.sh 5
Running: tor --RunAsDaemon 1 --CookieAuthentication 0 --HashedControlPassword "" --ControlPort 15001 --PidFile tor1.pid --SocksPort 9051 --DataDirectory data/tor1
Apr 09 05:48:57.036 [notice] Tor 0.3.5.8 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1b, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 09 05:48:57.036 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 09 05:48:57.036 [notice] Read configuration file "/etc/tor/torrc".
Apr 09 05:48:57.045 [warn] Skipping obsolete configuration option 'WarnUnsafeSocks'
Apr 09 05:48:57.045 [warn] Skipping obsolete configuration option 'AllowDotExit'
Apr 09 05:48:57.045 [warn] Linelist option '__HashedControlSessionPassword' has no value. Skipping.
Apr 09 05:48:57.045 [warn] Path for DataDirectory (data/tor1) is relative and will resolve to /root/Desktop/Multi-TOR/data/tor1. Is this what you wanted?
Apr 09 05:48:57.046 [warn] Path for PidFile (tor1.pid) is relative and will resolve to /root/Desktop/Multi-TOR/tor1.pid. Is this what you wanted?
Apr 09 05:48:57.046 [warn] Failed to parse/validate config: You have specified at least one relative path (see above) with the RunAsDaemon option. RunAsDaemon is not compatible with relative paths.
Apr 09 05:48:57.095 [err] Reading config failed--see warnings above.
root@kali:

**Comment by theraisin** [comment]
You didn't use the up address of your device

**Comment by jseidl** [comment]
Yeah it expects you to give a full absolute path in order to avoid vulnerabilities that come from relative paths.

**Comment by nullitall** [comment]
[SOLVED] this should fix it for you

`!/bin/bash

set -e
base_socks_port=9050

# Create data directory if it doesn't exist
if [ ! -d "data" ]; then
        mkdir "data"
fi

TOR_INSTANCES="$1"
#put your ip below if you want to access remotely otherwise remove $ipaddress: from below
#no need to do the old sh script 5 192.168.1.1
ip_addr=192.168.1.15

for i in $(seq $TOR_INSTANCES)
do
        j=$((i+1))
        socks_port=$((base_socks_port+i))
        if [ ! -d "/home/syco/data/tor$i" ]; then
                echo "Creating directory data/tor$i"
                mkdir "/home/syco/data/tor$i"
        fi

        # Take into account that authentication for the control port is disabled. Must be used in secure and controlled environments

        tor --RunAsDaemon 1 --CookieAuthentication 0 --PidFile /home/USERNAME/data/tor$i.pid --SocksPort $ip_addr:$socks_port --DataDirectory /home/USERNAME/data/tor$i
done
`

**Comment by nullitall** [comment]
`!/bin/bash
#making script to stop on 1st error
set -e

# Original script from
# http://blog.databigbang.com/distributed-scraping-with-multiple-tor-circuits/

base_socks_port=9050

# Create data directory if it doesn't exist
if [ ! -d "data" ]; then
        mkdir "data"
fi

TOR_INSTANCES="$1"
ip_addr=192.168.1.102
for i in $(seq $TOR_INSTANCES)
do
        j=$((i+1))
        socks_port=$((base_socks_port+i))
        if [ ! -d "/home/syco/data/tor$i" ]; then
                echo "Creating directory data/tor$i"
                mkdir "/home/syco/data/tor$i"
        fi

        # Take into account that authentication for the control port is disabled. Must be used in secure and controlled environments

        tor --RunAsDaemon 1 --CookieAuthentication 0 --PidFile /home/syco/data/tor$i.pid --SocksPort $ip_addr:$socks_port --DataDirectory /home/syco/data/tor$i
done
`

**Comment by nullitall** [comment]
heres a fix
https://github.com/nullitall/multitor
